export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT';
export const SET_ARTICLES_IS_LOADED = 'SET_ARTICLES_IS_LOADED';
export const SET_PAGE = 'SET_PAGE';
export const SET_ARTICLE = 'SET_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const SET_ARTICLE_IS_LOADED = 'SET_ARTICLE_IS_LOADED';
